services:
  - type: web
    name: rwanda-health-media-scanner
    env: python
    plan: free
    runtime: python-3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT webapp.app:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
